"""removed google_books_id from authors

Revision ID: 0ea6ec56b537
Revises: c476831a3194
Create Date: 2025-05-24 21:34:05.580975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ea6ec56b537'
down_revision: Union[str, None] = 'c476831a3194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('google_books_id', table_name='authors')
    op.drop_column('authors', 'google_books_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('google_books_id', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('google_books_id', 'authors', ['google_books_id'], unique=True)
    # ### end Alembic commands ###
