"""changed booksaleinfo column names

Revision ID: 67aa4347cdff
Revises: a3b4c1d8a491
Create Date: 2025-05-21 21:05:17.760325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67aa4347cdff'
down_revision: Union[str, None] = 'a3b4c1d8a491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_sale_info', sa.Column('list_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('book_sale_info', sa.Column('list_price_currency_code', sa.String(length=5), nullable=True))
    op.add_column('book_sale_info', sa.Column('retail_price_currency_code', sa.String(length=5), nullable=True))
    op.drop_column('book_sale_info', 'currency_code')
    op.drop_column('book_sale_info', 'price')
    op.drop_column('book_sale_info', 'retail_currency_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_sale_info', sa.Column('retail_currency_code', mysql.VARCHAR(length=5), nullable=True))
    op.add_column('book_sale_info', sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('book_sale_info', sa.Column('currency_code', mysql.VARCHAR(length=5), nullable=True))
    op.drop_column('book_sale_info', 'retail_price_currency_code')
    op.drop_column('book_sale_info', 'list_price_currency_code')
    op.drop_column('book_sale_info', 'list_price')
    # ### end Alembic commands ###
