"""added buy link to BookSaleInfo

Revision ID: 6a106cc5c369
Revises: 67aa4347cdff
Create Date: 2025-05-21 22:00:16.688101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a106cc5c369'
down_revision: Union[str, None] = '67aa4347cdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_sale_info', sa.Column('buy_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_sale_info', 'buy_link')
    # ### end Alembic commands ###
