"""Add token links to BookAccess

Revision ID: 76a85a955b1f
Revises: 0ea6ec56b537
Create Date: 2025-05-27 21:01:35.911549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a85a955b1f'
down_revision: Union[str, None] = '0ea6ec56b537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_access', sa.Column('epub_token_link', sa.String(length=255), nullable=True))
    op.add_column('book_access', sa.Column('pdf_token_link', sa.String(length=255), nullable=True))
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('book_access', 'pdf_token_link')
    op.drop_column('book_access', 'epub_token_link')
    # ### end Alembic commands ###
