"""add user_book_state

Revision ID: 937c2f2e0a4e
Revises: caa1cfd66674
Create Date: 2025-12-21 18:24:32.034975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937c2f2e0a4e'
down_revision: Union[str, Sequence[str], None] = 'caa1cfd66674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_book_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('reading_status', sa.Enum('WANT_TO_READ', 'READING', 'COMPLETED', 'ABANDONED', name='reading_status'), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('percent_complete', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='unique_user_book_state')
    )
    op.create_index(op.f('ix_user_book_state_book_id'), 'user_book_state', ['book_id'], unique=False)
    op.create_index(op.f('ix_user_book_state_id'), 'user_book_state', ['id'], unique=False)
    op.create_index(op.f('ix_user_book_state_user_id'), 'user_book_state', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_book_state_user_id'), table_name='user_book_state')
    op.drop_index(op.f('ix_user_book_state_id'), table_name='user_book_state')
    op.drop_index(op.f('ix_user_book_state_book_id'), table_name='user_book_state')
    op.drop_table('user_book_state')
    # ### end Alembic commands ###
