"""changed booksale to booksaleinfo

Revision ID: a3b4c1d8a491
Revises: 73c557458dac
Create Date: 2025-05-21 18:00:06.302098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a3b4c1d8a491'
down_revision: Union[str, None] = '73c557458dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_sale_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('saleability', sa.String(length=50), nullable=True),
    sa.Column('is_ebook', sa.Boolean(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=5), nullable=True),
    sa.Column('retail_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('retail_currency_code', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_sale_info_id'), 'book_sale_info', ['id'], unique=False)
    op.drop_index('ix_book_sales_id', table_name='book_sales')
    op.drop_table('book_sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_sales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('saleability', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_ebook', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency_code', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('retail_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('retail_currency_code', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_sales_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_book_sales_id', 'book_sales', ['id'], unique=False)
    op.drop_index(op.f('ix_book_sale_info_id'), table_name='book_sale_info')
    op.drop_table('book_sale_info')
    # ### end Alembic commands ###
