"""test

Revision ID: b525cc5b07c5
Revises: 20f71cde105e
Create Date: 2025-05-20 21:33:54.653178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b525cc5b07c5'
down_revision: Union[str, None] = '20f71cde105e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookcases_ibfk_1', 'bookcases', type_='foreignkey')
    op.create_foreign_key(None, 'bookcases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookcases', type_='foreignkey')
    op.create_foreign_key('bookcases_ibfk_1', 'bookcases', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
